/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReceptionIndexRouteImport } from './routes/reception.index'
import { Route as ManagementIndexRouteImport } from './routes/management.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as ReceptionWardsRouteImport } from './routes/reception.wards'
import { Route as ReceptionStaffRouteImport } from './routes/reception.staff'
import { Route as ReceptionQueueRouteImport } from './routes/reception.queue'
import { Route as ReceptionPatientsRouteImport } from './routes/reception.patients'
import { Route as ReceptionOpdRouteImport } from './routes/reception.opd'
import { Route as ReceptionDischargeRouteImport } from './routes/reception.discharge'
import { Route as ReceptionBirthRouteImport } from './routes/reception.birth'
import { Route as ReceptionBillingRouteImport } from './routes/reception.billing'
import { Route as ReceptionAdvancesRouteImport } from './routes/reception.advances'
import { Route as ReceptionAdmissionRouteImport } from './routes/reception.admission'
import { Route as ManagementWardsRouteImport } from './routes/management.wards'
import { Route as ManagementStaffRouteImport } from './routes/management.staff'
import { Route as ManagementDoctorsRouteImport } from './routes/management.doctors'
import { Route as ManagementBedsRouteImport } from './routes/management.beds'
import { Route as DoctorScheduleRouteImport } from './routes/doctor.schedule'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorPatientRouteImport } from './routes/doctor.patient'
import { Route as DoctorInvestigationsRouteImport } from './routes/doctor.investigations'
import { Route as DoctorHistoryRouteImport } from './routes/doctor.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionIndexRoute = ReceptionIndexRouteImport.update({
  id: '/reception/',
  path: '/reception/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementIndexRoute = ManagementIndexRouteImport.update({
  id: '/management/',
  path: '/management/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionWardsRoute = ReceptionWardsRouteImport.update({
  id: '/reception/wards',
  path: '/reception/wards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionStaffRoute = ReceptionStaffRouteImport.update({
  id: '/reception/staff',
  path: '/reception/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionQueueRoute = ReceptionQueueRouteImport.update({
  id: '/reception/queue',
  path: '/reception/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionPatientsRoute = ReceptionPatientsRouteImport.update({
  id: '/reception/patients',
  path: '/reception/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionOpdRoute = ReceptionOpdRouteImport.update({
  id: '/reception/opd',
  path: '/reception/opd',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionDischargeRoute = ReceptionDischargeRouteImport.update({
  id: '/reception/discharge',
  path: '/reception/discharge',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionBirthRoute = ReceptionBirthRouteImport.update({
  id: '/reception/birth',
  path: '/reception/birth',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionBillingRoute = ReceptionBillingRouteImport.update({
  id: '/reception/billing',
  path: '/reception/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionAdvancesRoute = ReceptionAdvancesRouteImport.update({
  id: '/reception/advances',
  path: '/reception/advances',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionAdmissionRoute = ReceptionAdmissionRouteImport.update({
  id: '/reception/admission',
  path: '/reception/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementWardsRoute = ManagementWardsRouteImport.update({
  id: '/management/wards',
  path: '/management/wards',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementStaffRoute = ManagementStaffRouteImport.update({
  id: '/management/staff',
  path: '/management/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementDoctorsRoute = ManagementDoctorsRouteImport.update({
  id: '/management/doctors',
  path: '/management/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementBedsRoute = ManagementBedsRouteImport.update({
  id: '/management/beds',
  path: '/management/beds',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/doctor/schedule',
  path: '/doctor/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/doctor/profile',
  path: '/doctor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/doctor/patients',
  path: '/doctor/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientRoute = DoctorPatientRouteImport.update({
  id: '/doctor/patient',
  path: '/doctor/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorInvestigationsRoute = DoctorInvestigationsRouteImport.update({
  id: '/doctor/investigations',
  path: '/doctor/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorHistoryRoute = DoctorHistoryRouteImport.update({
  id: '/doctor/history',
  path: '/doctor/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor/history': typeof DoctorHistoryRoute
  '/doctor/investigations': typeof DoctorInvestigationsRoute
  '/doctor/patient': typeof DoctorPatientRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/management/beds': typeof ManagementBedsRoute
  '/management/doctors': typeof ManagementDoctorsRoute
  '/management/staff': typeof ManagementStaffRoute
  '/management/wards': typeof ManagementWardsRoute
  '/reception/admission': typeof ReceptionAdmissionRoute
  '/reception/advances': typeof ReceptionAdvancesRoute
  '/reception/billing': typeof ReceptionBillingRoute
  '/reception/birth': typeof ReceptionBirthRoute
  '/reception/discharge': typeof ReceptionDischargeRoute
  '/reception/opd': typeof ReceptionOpdRoute
  '/reception/patients': typeof ReceptionPatientsRoute
  '/reception/queue': typeof ReceptionQueueRoute
  '/reception/staff': typeof ReceptionStaffRoute
  '/reception/wards': typeof ReceptionWardsRoute
  '/doctor/': typeof DoctorIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/reception/': typeof ReceptionIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctor/history': typeof DoctorHistoryRoute
  '/doctor/investigations': typeof DoctorInvestigationsRoute
  '/doctor/patient': typeof DoctorPatientRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/management/beds': typeof ManagementBedsRoute
  '/management/doctors': typeof ManagementDoctorsRoute
  '/management/staff': typeof ManagementStaffRoute
  '/management/wards': typeof ManagementWardsRoute
  '/reception/admission': typeof ReceptionAdmissionRoute
  '/reception/advances': typeof ReceptionAdvancesRoute
  '/reception/billing': typeof ReceptionBillingRoute
  '/reception/birth': typeof ReceptionBirthRoute
  '/reception/discharge': typeof ReceptionDischargeRoute
  '/reception/opd': typeof ReceptionOpdRoute
  '/reception/patients': typeof ReceptionPatientsRoute
  '/reception/queue': typeof ReceptionQueueRoute
  '/reception/staff': typeof ReceptionStaffRoute
  '/reception/wards': typeof ReceptionWardsRoute
  '/doctor': typeof DoctorIndexRoute
  '/management': typeof ManagementIndexRoute
  '/reception': typeof ReceptionIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor/history': typeof DoctorHistoryRoute
  '/doctor/investigations': typeof DoctorInvestigationsRoute
  '/doctor/patient': typeof DoctorPatientRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/management/beds': typeof ManagementBedsRoute
  '/management/doctors': typeof ManagementDoctorsRoute
  '/management/staff': typeof ManagementStaffRoute
  '/management/wards': typeof ManagementWardsRoute
  '/reception/admission': typeof ReceptionAdmissionRoute
  '/reception/advances': typeof ReceptionAdvancesRoute
  '/reception/billing': typeof ReceptionBillingRoute
  '/reception/birth': typeof ReceptionBirthRoute
  '/reception/discharge': typeof ReceptionDischargeRoute
  '/reception/opd': typeof ReceptionOpdRoute
  '/reception/patients': typeof ReceptionPatientsRoute
  '/reception/queue': typeof ReceptionQueueRoute
  '/reception/staff': typeof ReceptionStaffRoute
  '/reception/wards': typeof ReceptionWardsRoute
  '/doctor/': typeof DoctorIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/reception/': typeof ReceptionIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor/history'
    | '/doctor/investigations'
    | '/doctor/patient'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/management/beds'
    | '/management/doctors'
    | '/management/staff'
    | '/management/wards'
    | '/reception/admission'
    | '/reception/advances'
    | '/reception/billing'
    | '/reception/birth'
    | '/reception/discharge'
    | '/reception/opd'
    | '/reception/patients'
    | '/reception/queue'
    | '/reception/staff'
    | '/reception/wards'
    | '/doctor/'
    | '/management/'
    | '/reception/'
    | '/reports/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doctor/history'
    | '/doctor/investigations'
    | '/doctor/patient'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/management/beds'
    | '/management/doctors'
    | '/management/staff'
    | '/management/wards'
    | '/reception/admission'
    | '/reception/advances'
    | '/reception/billing'
    | '/reception/birth'
    | '/reception/discharge'
    | '/reception/opd'
    | '/reception/patients'
    | '/reception/queue'
    | '/reception/staff'
    | '/reception/wards'
    | '/doctor'
    | '/management'
    | '/reception'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/doctor/history'
    | '/doctor/investigations'
    | '/doctor/patient'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/management/beds'
    | '/management/doctors'
    | '/management/staff'
    | '/management/wards'
    | '/reception/admission'
    | '/reception/advances'
    | '/reception/billing'
    | '/reception/birth'
    | '/reception/discharge'
    | '/reception/opd'
    | '/reception/patients'
    | '/reception/queue'
    | '/reception/staff'
    | '/reception/wards'
    | '/doctor/'
    | '/management/'
    | '/reception/'
    | '/reports/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorHistoryRoute: typeof DoctorHistoryRoute
  DoctorInvestigationsRoute: typeof DoctorInvestigationsRoute
  DoctorPatientRoute: typeof DoctorPatientRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  ManagementBedsRoute: typeof ManagementBedsRoute
  ManagementDoctorsRoute: typeof ManagementDoctorsRoute
  ManagementStaffRoute: typeof ManagementStaffRoute
  ManagementWardsRoute: typeof ManagementWardsRoute
  ReceptionAdmissionRoute: typeof ReceptionAdmissionRoute
  ReceptionAdvancesRoute: typeof ReceptionAdvancesRoute
  ReceptionBillingRoute: typeof ReceptionBillingRoute
  ReceptionBirthRoute: typeof ReceptionBirthRoute
  ReceptionDischargeRoute: typeof ReceptionDischargeRoute
  ReceptionOpdRoute: typeof ReceptionOpdRoute
  ReceptionPatientsRoute: typeof ReceptionPatientsRoute
  ReceptionQueueRoute: typeof ReceptionQueueRoute
  ReceptionStaffRoute: typeof ReceptionStaffRoute
  ReceptionWardsRoute: typeof ReceptionWardsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  ManagementIndexRoute: typeof ManagementIndexRoute
  ReceptionIndexRoute: typeof ReceptionIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/': {
      id: '/reception/'
      path: '/reception'
      fullPath: '/reception/'
      preLoaderRoute: typeof ReceptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/': {
      id: '/management/'
      path: '/management'
      fullPath: '/management/'
      preLoaderRoute: typeof ManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/wards': {
      id: '/reception/wards'
      path: '/reception/wards'
      fullPath: '/reception/wards'
      preLoaderRoute: typeof ReceptionWardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/staff': {
      id: '/reception/staff'
      path: '/reception/staff'
      fullPath: '/reception/staff'
      preLoaderRoute: typeof ReceptionStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/queue': {
      id: '/reception/queue'
      path: '/reception/queue'
      fullPath: '/reception/queue'
      preLoaderRoute: typeof ReceptionQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/patients': {
      id: '/reception/patients'
      path: '/reception/patients'
      fullPath: '/reception/patients'
      preLoaderRoute: typeof ReceptionPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/opd': {
      id: '/reception/opd'
      path: '/reception/opd'
      fullPath: '/reception/opd'
      preLoaderRoute: typeof ReceptionOpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/discharge': {
      id: '/reception/discharge'
      path: '/reception/discharge'
      fullPath: '/reception/discharge'
      preLoaderRoute: typeof ReceptionDischargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/birth': {
      id: '/reception/birth'
      path: '/reception/birth'
      fullPath: '/reception/birth'
      preLoaderRoute: typeof ReceptionBirthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/billing': {
      id: '/reception/billing'
      path: '/reception/billing'
      fullPath: '/reception/billing'
      preLoaderRoute: typeof ReceptionBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/advances': {
      id: '/reception/advances'
      path: '/reception/advances'
      fullPath: '/reception/advances'
      preLoaderRoute: typeof ReceptionAdvancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/admission': {
      id: '/reception/admission'
      path: '/reception/admission'
      fullPath: '/reception/admission'
      preLoaderRoute: typeof ReceptionAdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/wards': {
      id: '/management/wards'
      path: '/management/wards'
      fullPath: '/management/wards'
      preLoaderRoute: typeof ManagementWardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/staff': {
      id: '/management/staff'
      path: '/management/staff'
      fullPath: '/management/staff'
      preLoaderRoute: typeof ManagementStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/doctors': {
      id: '/management/doctors'
      path: '/management/doctors'
      fullPath: '/management/doctors'
      preLoaderRoute: typeof ManagementDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/beds': {
      id: '/management/beds'
      path: '/management/beds'
      fullPath: '/management/beds'
      preLoaderRoute: typeof ManagementBedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/doctor/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patient': {
      id: '/doctor/patient'
      path: '/doctor/patient'
      fullPath: '/doctor/patient'
      preLoaderRoute: typeof DoctorPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/investigations': {
      id: '/doctor/investigations'
      path: '/doctor/investigations'
      fullPath: '/doctor/investigations'
      preLoaderRoute: typeof DoctorInvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/history': {
      id: '/doctor/history'
      path: '/doctor/history'
      fullPath: '/doctor/history'
      preLoaderRoute: typeof DoctorHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorHistoryRoute: DoctorHistoryRoute,
  DoctorInvestigationsRoute: DoctorInvestigationsRoute,
  DoctorPatientRoute: DoctorPatientRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  ManagementBedsRoute: ManagementBedsRoute,
  ManagementDoctorsRoute: ManagementDoctorsRoute,
  ManagementStaffRoute: ManagementStaffRoute,
  ManagementWardsRoute: ManagementWardsRoute,
  ReceptionAdmissionRoute: ReceptionAdmissionRoute,
  ReceptionAdvancesRoute: ReceptionAdvancesRoute,
  ReceptionBillingRoute: ReceptionBillingRoute,
  ReceptionBirthRoute: ReceptionBirthRoute,
  ReceptionDischargeRoute: ReceptionDischargeRoute,
  ReceptionOpdRoute: ReceptionOpdRoute,
  ReceptionPatientsRoute: ReceptionPatientsRoute,
  ReceptionQueueRoute: ReceptionQueueRoute,
  ReceptionStaffRoute: ReceptionStaffRoute,
  ReceptionWardsRoute: ReceptionWardsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  ManagementIndexRoute: ManagementIndexRoute,
  ReceptionIndexRoute: ReceptionIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
